version: '3'
services:

  api:
    build: backend
    ports:
    - "5000:5000"
    links:
    - db
    depends_on:
    - db
    environment:
    - POSTGRES_USER=foo
    - POSTGRES_PASSWORD=bar
    - POSTGRES_HOST=db
    - SLACK_OAUTH_TOKEN=${SLACK_OAUTH_TOKEN}
    - KICKERSCORE_CHANNEL_ID=${KICKERSCORE_CHANNEL_ID}

  db:
    image: postgres:10.5-alpine
    environment:
    - POSTGRES_USER=foo
    - POSTGRES_PASSWORD=bar
    - POSTGRES_DB=kickerscore

  migrator:
    build: backend
    links:
    - db
    depends_on:
    - db
    environment:
    - POSTGRES_USER=foo
    - POSTGRES_PASSWORD=bar
    - POSTGRES_HOST=db
    - FLASK_APP=/app/app
    - SLACK_OAUTH_TOKEN=${SLACK_OAUTH_TOKEN}
    - KICKERSCORE_CHANNEL_ID=${KICKERSCORE_CHANNEL_ID}
    command: "flask db upgrade -d /app/migrations"
    restart: on-failure

  frontend:
    build: frontend
    ports:
    - "3000:3000"
    links:
    - api
    depends_on:
    - api
    environment:
    - REACT_APP_API_HOST=localhost
    - REACT_APP_API_PORT=5000
    - REACT_APP_API_SUBDIR=