---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: traefik

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: traefik

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: traefik
  labels:
    app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-ingress-lb
  template:
    metadata:
      labels:
        app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        resources:
          limits:
            nvidia.com/gpu: 0
            memory: "1024Mi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "0.1"
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO

---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: traefik
spec:
  selector:
    app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  externalIPs:
    - 192.168.3.9
    - 10.8.0.1

---
kind: Service
apiVersion: v1
metadata:
  name: traefik-admin-service
  namespace: traefik
spec:
  selector:
    app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: admin

---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-admin-auth-secret
  namespace: traefik
type: Opaque
data:
  auth: "[hidden for git]"

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-admin-ingress
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: traefik-admin-auth-secret
spec:
  rules:
  - http:
      paths:
      - path: /traefik
        backend:
          serviceName: traefik-admin-service
          servicePort: 8080
