---
apiVersion: v1
kind: Namespace
metadata:
  name: kickerscore

---
apiVersion: v1
kind: Service
metadata:
  name: kickerscore-db-service
  namespace: kickerscore
  labels:
    app: kickerscore
    tier: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: kickerscore
    tier: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: kickerscore-backend-service
  namespace: kickerscore
  labels:
    app: kickerscore
    tier: backend
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: kickerscore
    tier: backend

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kickerscore-pv
  namespace: kickerscore
  labels:
    app: kickerscore
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/kickerscore"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: kickerscore
  labels:
    app: kickerscore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kickerscore
type: Opaque
data:
  username: "[hidden for git]"
  password: "[hidden for git]"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickerscore-db-deployment
  namespace: kickerscore
  labels:
    app: kickerscore
    tier: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kickerscore
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kickerscore
        tier: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgres
        env:
          - name: "POSTGRES_USER"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: "POSTGRES_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kickerscore-deployment
  namespace: kickerscore
  labels:
    app: kickerscore
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kickerscore
      tier: backend
  template:
    metadata:
      labels:
        app: kickerscore
        tier: backend
    spec:
      containers:
      - name: kickerscore-backend
        image: 10.8.0.1:30000/sreitsma/kickerscore:latest
        ports:
          - containerPort: 5000
        resources:
          limits:
            nvidia.com/gpu: 0
            memory: "1024Mi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "0.1"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15
        env:
          - name: "POSTGRES_USER"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: "POSTGRES_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kickerscore-ingress
  namespace: kickerscore
spec:
  rules:
  - http:
      paths:
      - path: /kickerscore
        backend:
          serviceName: kickerscore-backend-service
          servicePort: 5000
