version: '3'
services:

  api:
    build: .
    ports:
    - "5000:5000"
    links:
    - db
    depends_on:
    - db
    environment:
    - POSTGRES_USER=foo
    - POSTGRES_PASSWORD=bar
    - POSTGRES_HOST=db

  db:
    image: postgres
    environment:
    - POSTGRES_USER=foo
    - POSTGRES_PASSWORD=bar
    - POSTGRES_DB=kickerscore

  migrator:
    build: .
    links:
    - db
    depends_on:
    - db
    environment:
    - POSTGRES_USER=foo
    - POSTGRES_PASSWORD=bar
    - POSTGRES_HOST=db
    - FLASK_APP=opt/app/app
    command: "flask db upgrade -d opt/app/migrations"
    restart: on-failure
