name: kickerscore
dependencies:
  - python=3.6.6
  - zlib
  - numpy=1.16.0
  - pandas=0.24.1
  - APScheduler=3.5.3
  - flask-restful=0.3.6
  - flask-sqlalchemy=2.3.2
  - flask-cors=3.0.6
  - flask-migrate=2.3.1
  - flask-testing=0.7.1
  - slackclient=1.3.0
  - pillow
  - scipy>=0.17.0
  - click>=6.0
  - dlib>=19.7
  - pip
  - pip:
    - -r requirements.txt
channels:
  - defaults
  - conda-forge
