version: 2.0
jobs:
  backend:
    machine: yes
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t bigdatarepublic/kickerscore:$CIRCLE_BRANCH backend/
      - run: docker push bigdatarepublic/kickerscore:$CIRCLE_BRANCH
  frontend:
    machine: yes
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t bigdatarepublic/kickerscore:$CIRCLE_BRANCH frontend/
      - run: docker push bigdatarepublic/kickerscore:$CIRCLE_BRANCH
workflows:
  version: 2
  build:
    jobs:
      - backend
      - frontend
