version: 2.0
jobs:
  backend:
    machine: yes
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t bigdatarepublic/kickerscore:$CIRCLE_BRANCH backend/

      - run: |
          docker run -d \
            -e POSTGRES_USER=foo \
            -e POSTGRES_PASSWORD=bar \
            -e POSTGRES_DB=kickerscore \
            postgres:10.5-alpine
      - run: docker run bigdatarepublic/kickerscore:$CIRCLE_BRANCH python tests.py

      - run: docker push bigdatarepublic/kickerscore:$CIRCLE_BRANCH
  frontend:
    machine: yes
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t bigdatarepublic/kickerscore:$CIRCLE_BRANCH frontend/
      - run: docker push bigdatarepublic/kickerscore:$CIRCLE_BRANCH
workflows:
  version: 2
  build:
    jobs:
      - backend
      - frontend
