version: 2.0
jobs:
  backend:
    machine: yes
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: docker build -t bigdatarepublic/kickerscore:$CIRCLE_SHA1 backend/

      #- run: |
      #    docker run -d \
      #      -e POSTGRES_USER=foo \
      #      -e POSTGRES_PASSWORD=bar \
      #      -e POSTGRES_DB=kickerscore \
      #      postgres:10.5-alpine
      #- run: |
      #    docker run \
      #      -e POSTGRES_USER=foo \
      #      -e POSTGRES_PASSWORD=bar \
      #      -e POSTGRES_HOST=localhost \
      #      -e SLACK_OAUTH_TOKEN=${SLACK_OAUTH_TOKEN} \
      #      -e KICKERSCORE_CHANNEL_ID=${KICKERSCORE_CHANNEL_ID} \
      #      -e FLASK_APP=/mnt/src/app \
      #      -v backend:/mnt \
      #      -w /mnt/tests \
      #      bigdatarepublic/kickerscore:$CIRCLE_SHA1 python tests.py

      - run: docker push bigdatarepublic/kickerscore:$CIRCLE_SHA1
  frontend:
    machine: yes
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t bigdatarepublic/kickerscore-frontend:$CIRCLE_SHA1 frontend/
      - run: docker push bigdatarepublic/kickerscore-frontend:$CIRCLE_SHA1
workflows:
  version: 2
  build:
    jobs:
      - backend
      - frontend
