version: 2.0
jobs:
  build:
    machine: yes
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t bigdatarepublic/kickerscore:$CIRCLE_BRANCH backend/
      - run: docker push bigdatarepublic/kickerscore:$CIRCLE_BRANCH
