"""empty message

Revision ID: 315a1a496373
Revises: 
Create Date: 2018-08-10 15:52:18.743565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315a1a496373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('rating_mu', sa.Float(), nullable=False),
    sa.Column('rating_sigma', sa.Float(), nullable=False),
    sa.Column('rating_mu_offense', sa.Float(), nullable=False),
    sa.Column('rating_sigma_offense', sa.Float(), nullable=False),
    sa.Column('rating_mu_defense', sa.Float(), nullable=False),
    sa.Column('rating_sigma_defense', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blue_offense_player', sa.String(length=32), nullable=True),
    sa.Column('blue_defense_player', sa.String(length=32), nullable=True),
    sa.Column('red_offense_player', sa.String(length=32), nullable=True),
    sa.Column('red_defense_player', sa.String(length=32), nullable=True),
    sa.Column('blue_points', sa.Integer(), nullable=True),
    sa.Column('red_points', sa.Integer(), nullable=True),
    sa.Column('predicted_win_prob_for_blue', sa.Float(), nullable=True),
    sa.Column('match_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['blue_defense_player'], ['player.username'], ),
    sa.ForeignKeyConstraint(['blue_offense_player'], ['player.username'], ),
    sa.ForeignKeyConstraint(['red_defense_player'], ['player.username'], ),
    sa.ForeignKeyConstraint(['red_offense_player'], ['player.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('player')
    # ### end Alembic commands ###
