"""empty message

Revision ID: a444f1adee2d
Revises: 4fbec16ea6e8
Create Date: 2018-10-25 20:31:56.552695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a444f1adee2d'
down_revision = '4fbec16ea6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('player', 'old_player')
    op.rename_table('match', 'old_match')

    op.create_table('player',
    sa.Column('slack_id', sa.String(length=16), nullable=False),
    sa.Column('slack_username', sa.String(length=64), nullable=True),
    sa.Column('slack_avatar', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('rating_mu', sa.Float(), nullable=False),
    sa.Column('rating_sigma', sa.Float(), nullable=False),
    sa.Column('rating_mu_offense', sa.Float(), nullable=False),
    sa.Column('rating_sigma_offense', sa.Float(), nullable=False),
    sa.Column('rating_mu_defense', sa.Float(), nullable=False),
    sa.Column('rating_sigma_defense', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False, default=True),
    sa.PrimaryKeyConstraint('slack_id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blue_offense_player', sa.String(length=32), nullable=True),
    sa.Column('blue_defense_player', sa.String(length=32), nullable=True),
    sa.Column('red_offense_player', sa.String(length=32), nullable=True),
    sa.Column('red_defense_player', sa.String(length=32), nullable=True),
    sa.Column('blue_offense_player_skill_gain_overall', sa.Float(), nullable=True),
    sa.Column('blue_defense_player_skill_gain_overall', sa.Float(), nullable=True),
    sa.Column('blue_offense_player_skill_gain_offense', sa.Float(), nullable=True),
    sa.Column('blue_defense_player_skill_gain_defense', sa.Float(), nullable=True),
    sa.Column('red_offense_player_skill_gain_overall', sa.Float(), nullable=True),
    sa.Column('red_defense_player_skill_gain_overall', sa.Float(), nullable=True),
    sa.Column('red_offense_player_skill_gain_offense', sa.Float(), nullable=True),
    sa.Column('red_defense_player_skill_gain_defense', sa.Float(), nullable=True),
    sa.Column('blue_points', sa.Integer(), nullable=True),
    sa.Column('red_points', sa.Integer(), nullable=True),
    sa.Column('predicted_win_prob_for_blue', sa.Float(), nullable=True),
    sa.Column('match_balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['blue_defense_player'], ['player.slack_id'], ),
    sa.ForeignKeyConstraint(['blue_offense_player'], ['player.slack_id'], ),
    sa.ForeignKeyConstraint(['red_defense_player'], ['player.slack_id'], ),
    sa.ForeignKeyConstraint(['red_offense_player'], ['player.slack_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('player')
    op.rename_table('old_match', 'match')
    op.rename_table('old_player', 'player')
    # ### end Alembic commands ###
