"""empty message

Revision ID: a4c56215d944
Revises: 
Create Date: 2019-02-07 15:29:49.156168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c56215d944'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('blue_points', sa.Integer(), nullable=True),
                    sa.Column('red_points', sa.Integer(), nullable=True),
                    sa.Column('predicted_win_prob_for_blue',
                              sa.Float(), nullable=True),
                    sa.Column('match_balance', sa.Float(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('player',
                    sa.Column('slack_id', sa.String(
                        length=16), nullable=False),
                    sa.Column('slack_username', sa.String(
                        length=64), nullable=True),
                    sa.Column('slack_avatar', sa.Text(), nullable=True),
                    sa.Column('registration_date',
                              sa.DateTime(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('rating_mu', sa.Float(), nullable=False),
                    sa.Column('rating_sigma', sa.Float(), nullable=False),
                    sa.Column('rating_mu_offense', sa.Float(), nullable=False),
                    sa.Column('rating_sigma_offense',
                              sa.Float(), nullable=False),
                    sa.Column('rating_mu_defense', sa.Float(), nullable=False),
                    sa.Column('rating_sigma_defense',
                              sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('slack_id')
                    )
    op.create_table('match_participant',
                    sa.Column('user_id', sa.String(length=16), nullable=False),
                    sa.Column('match_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('team', sa.String(length=4), nullable=True),
                    sa.Column('position', sa.String(length=7), nullable=True),
                    sa.Column('overall_skill_gain', sa.Float(), nullable=True),
                    sa.Column('offense_skill_gain', sa.Float(), nullable=True),
                    sa.Column('defense_skill_gain', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['player.slack_id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'match_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_participant')
    op.drop_table('player')
    op.drop_table('match')
    # ### end Alembic commands ###
