"""empty message

Revision ID: b4312fa1e808
Revises: a4c56215d944
Create Date: 2019-09-20 11:43:11.802481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4312fa1e808'
down_revision = 'a4c56215d944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_encoding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=16), nullable=True),
    sa.Column('encoding', sa.ARRAY(sa.Float()), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.slack_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_encoding')
    # ### end Alembic commands ###
